//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen.dll version:
//           7.1.2-build.15+g2b49bb9edc
//       
//       Command:
//           LottieGen.dll -Language CSharp -MinimumUapVersion 13 -Public -WinUIVersion 2.7 -InputFile Lottie.json
//       
//       Input file:
//           Lottie.json (13375 bytes created 14:41-07:00 Jun. 13 2022)
//       
//       LottieGen.dll source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   170 |
// |--------------------------+-------|
// | Expression animators     |    28 |
// | KeyFrame animators       |    16 |
// | Reference parameters     |    34 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     3 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |    13 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     3 |
// | ShapeVisuals             |     3 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |    11 |
// |--------------------------+-------|
// | Brushes                  |    12 |
// | Gradient stops           |     3 |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    // Name:        Comp 1
    // Frame rate:  29.9700012207031 fps
    // Frame count: 150.000006109625
    // Duration:    5005.0 mS
    sealed class CodeGen
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 5.005 seconds.
        internal const long c_durationTicks = 50050050;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (CodeGen_AnimatedVisual.IsRuntimeCompatible())
            {
                var res = 
                    new CodeGen_AnimatedVisual(
                        compositor
                        );
                    res.CreateAnimations();
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 150.000006109625;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 29.9700012207031;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 150.000006109625;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class CodeGen_AnimatedVisual : Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 50050050;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorGradientStop _gradientStop_0_Red;
            CompositionColorGradientStop _gradientStop_1_AlmostDarkBlue_FF0030AC;
            CompositionLinearGradientBrush _linearGradientBrush_2;
            CompositionLinearGradientBrush _linearGradientBrush_4;
            CompositionLinearGradientBrush _linearGradientBrush_5;
            CompositionRectangleGeometry _rectangle_0;
            CompositionRectangleGeometry _rectangle_1;
            CompositionRectangleGeometry _rectangle_2;
            CompositionRectangleGeometry _rectangle_150_0;
            CompositionRectangleGeometry _rectangle_150_1;
            CompositionRoundedRectangleGeometry _roundedRectangle_150_0;
            CompositionRoundedRectangleGeometry _roundedRectangle_150_1;
            CompositionRoundedRectangleGeometry _roundedRectangle_150_2;
            CompositionSpriteShape _spriteShape_06;
            CompositionSpriteShape _spriteShape_07;
            ContainerVisual _root;
            ExpressionAnimation _rootProgress;
            InsetClip _insetClip_0;
            LinearEasingFunction _linearEasingFunction_0;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_9_to_9;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _endPointSourceVector2Animation;
            Vector2KeyFrameAnimation _positionVector2Animation_3;
            Vector2KeyFrameAnimation _sizeVector2Animation_1;
            Vector2KeyFrameAnimation _startPointSourceVector2Animation;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            void BindProperty2(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName0,
                CompositionObject referencedObject0,
                string referenceParameterName1,
                CompositionObject referencedObject1)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName0, referencedObject0);
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName1, referencedObject1);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - Layer aggregator
            // - -  RotationDegrees:9, Offset:<590, 572>
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-324.709991F, 225.572998F));
                    builder.AddLine(new Vector2(-439.576996F, 280.214996F));
                    builder.AddLine(new Vector2(-402.381989F, 438.342987F));
                    builder.AddLine(new Vector2(-264.516998F, 426.631989F));
                    builder.AddLine(new Vector2(-271.730988F, 342.727997F));
                    builder.AddLine(new Vector2(-197.311005F, 288.416992F));
                    builder.AddLine(new Vector2(-324.709991F, 225.572998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Transforms for White Solid 1 Scale(1,1,0)
            CompositionColorBrush ColorBrush_White()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF));
            }

            // Stop 0
            CompositionColorGradientStop GradientStop_0_Red()
            {
                return (_gradientStop_0_Red == null)
                    ? _gradientStop_0_Red = _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0xFF, 0x00, 0x00))
                    : _gradientStop_0_Red;
            }

            // Stop 1
            CompositionColorGradientStop GradientStop_0p485_AlmostYellow_FFE3FF2C()
            {
                return _c.CreateColorGradientStop(0.485000014F, Color.FromArgb(0xFF, 0xE3, 0xFF, 0x2C));
            }

            // Stop 1
            CompositionColorGradientStop GradientStop_1_AlmostDarkBlue_FF0030AC()
            {
                return (_gradientStop_1_AlmostDarkBlue_FF0030AC == null)
                    ? _gradientStop_1_AlmostDarkBlue_FF0030AC = _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x00, 0x30, 0xAC))
                    : _gradientStop_1_AlmostDarkBlue_FF0030AC;
            }

            // - - PreComp layer: Static Rects
            // - Layer aggregator
            // RotationDegrees:9, Offset:<134, 128>
            CompositionLinearGradientBrush LinearGradientBrush_0()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(53F, 67F);
                result.EndPoint = new Vector2(95F, 106F);
                return result;
            }

            // - - PreComp layer: Static Rects
            // - Layer aggregator
            // RotationDegrees:9, Offset:<482, 129>
            CompositionLinearGradientBrush LinearGradientBrush_1()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-22F, 12F);
                result.EndPoint = new Vector2(20F, 51F);
                return result;
            }

            CompositionLinearGradientBrush LinearGradientBrush_2()
            {
                if (_linearGradientBrush_2 != null) { return _linearGradientBrush_2; }
                var result = _linearGradientBrush_2 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertVector2("EndPointSource", new Vector2(20F, 51F));
                propertySet.InsertVector2("StartPointSource", new Vector2(-22F, 12F));
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                BindProperty2(_linearGradientBrush_2, "StartPoint", "my.StartPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_150_1(), "my", _linearGradientBrush_2);
                BindProperty2(_linearGradientBrush_2, "EndPoint", "my.EndPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_150_1(), "my", _linearGradientBrush_2);
                return result;
            }

            // - - PreComp layer: Animated Rects
            // - Layer aggregator
            // Rectangle Path 1
            CompositionLinearGradientBrush LinearGradientBrush_3()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-22F, 12F);
                result.EndPoint = new Vector2(20F, 51F);
                return result;
            }

            CompositionLinearGradientBrush LinearGradientBrush_4()
            {
                if (_linearGradientBrush_4 != null) { return _linearGradientBrush_4; }
                var result = _linearGradientBrush_4 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertVector2("EndPointSource", new Vector2(20F, 20F));
                propertySet.InsertVector2("StartPointSource", new Vector2(-22F, -20F));
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                BindProperty2(_linearGradientBrush_4, "StartPoint", "my.StartPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_1(), "my", _linearGradientBrush_4);
                BindProperty2(_linearGradientBrush_4, "EndPoint", "my.EndPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_1(), "my", _linearGradientBrush_4);
                return result;
            }

            CompositionLinearGradientBrush LinearGradientBrush_5()
            {
                if (_linearGradientBrush_5 != null) { return _linearGradientBrush_5; }
                var result = _linearGradientBrush_5 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertVector2("EndPointSource", new Vector2(20F, 20F));
                propertySet.InsertVector2("StartPointSource", new Vector2(-22F, -20F));
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_0p485_AlmostYellow_FFE3FF2C());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                BindProperty2(_linearGradientBrush_5, "StartPoint", "my.StartPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_2(), "my", _linearGradientBrush_5);
                BindProperty2(_linearGradientBrush_5, "EndPoint", "my.EndPointSource+(Vector2(0,0)-geometry.Offset)", "geometry", Rectangle_2(), "my", _linearGradientBrush_5);
                return result;
            }

            // - Layer aggregator
            // RotationDegrees:9, Offset:<590, 572>
            CompositionLinearGradientBrush LinearGradientBrush_6()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(54F, 276F);
                result.EndPoint = new Vector2(55F, 348F);
                return result;
            }

            // - Layer aggregator
            // RotationDegrees:9, Offset:<590, 572>
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // - - PreComp layer: Static Rects
            // - Layer aggregator
            // RotationDegrees:9, Offset:<312, 128>
            CompositionRadialGradientBrush RadialGradientBrush_0()
            {
                var result = _c.CreateRadialGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.EllipseCenter = new Vector2(25F, 0F);
                result.EllipseRadius = new Vector2(50F, 50F);
                return result;
            }

            // - - PreComp layer: Static Rects
            // - Layer aggregator
            // RotationDegrees:9, Offset:<660, 129>
            CompositionRadialGradientBrush RadialGradientBrush_1()
            {
                var result = _c.CreateRadialGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.EllipseCenter = new Vector2(25F, 0F);
                result.EllipseRadius = new Vector2(50F, 50F);
                return result;
            }

            // - - PreComp layer: Animated Rects
            // - Layer aggregator
            // RotationDegrees:9, Offset:<308, 342>
            CompositionRadialGradientBrush RadialGradientBrush_2()
            {
                var result = _c.CreateRadialGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.EllipseCenter = new Vector2(25F, 0F);
                result.EllipseRadius = new Vector2(50F, 50F);
                return result;
            }

            // - - PreComp layer: Animated Rects
            // - Layer aggregator
            // Rectangle Path 1
            CompositionRadialGradientBrush RadialGradientBrush_3()
            {
                var result = _c.CreateRadialGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_Red());
                colorStops.Add(GradientStop_1_AlmostDarkBlue_FF0030AC());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.EllipseCenter = new Vector2(25F, 0F);
                result.EllipseRadius = new Vector2(50F, 50F);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_0()
            {
                if (_rectangle_0 != null) { return _rectangle_0; }
                var result = _rectangle_0 = _c.CreateRectangleGeometry();
                result.Offset = new Vector2(-75F, -55F);
                BindProperty(_rectangle_0, "Offset", "Vector2(0,20)-(my.Size/Vector2(2,2))", "my", _rectangle_0);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_1()
            {
                if (_rectangle_1 != null) { return _rectangle_1; }
                var result = _rectangle_1 = _c.CreateRectangleGeometry();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(0F, 0F));
                result.Offset = new Vector2(-75F, -75F);
                BindProperty(_rectangle_1, "Offset", "my.Position-(my.Size/Vector2(2,2))", "my", _rectangle_1);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_2()
            {
                if (_rectangle_2 != null) { return _rectangle_2; }
                var result = _rectangle_2 = _c.CreateRectangleGeometry();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(0F, 0F));
                result.Offset = new Vector2(-75F, -75F);
                BindProperty(_rectangle_2, "Offset", "my.Position-(my.Size/Vector2(2,2))", "my", _rectangle_2);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_150_0()
            {
                if (_rectangle_150_0 != null) { return _rectangle_150_0; }
                var result = _rectangle_150_0 = _c.CreateRectangleGeometry();
                result.Offset = new Vector2(-75F, -55F);
                result.Size = new Vector2(150F, 150F);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRectangleGeometry Rectangle_150_1()
            {
                if (_rectangle_150_1 != null) { return _rectangle_150_1; }
                var result = _rectangle_150_1 = _c.CreateRectangleGeometry();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(0F, 20F));
                result.Offset = new Vector2(-75F, -55F);
                result.Size = new Vector2(150F, 150F);
                BindProperty(_rectangle_150_1, "Offset", "my.Position-Vector2(75,75)", "my", _rectangle_150_1);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_150_0()
            {
                if (_roundedRectangle_150_0 != null) { return _roundedRectangle_150_0; }
                var result = _roundedRectangle_150_0 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(25F, 25F);
                result.Offset = new Vector2(-75F, -55F);
                result.Size = new Vector2(150F, 150F);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_150_1()
            {
                if (_roundedRectangle_150_1 != null) { return _roundedRectangle_150_1; }
                var result = _roundedRectangle_150_1 = _c.CreateRoundedRectangleGeometry();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(0F, 20F));
                result.CornerRadius = new Vector2(25F, 25F);
                result.Offset = new Vector2(-75F, -55F);
                result.Size = new Vector2(150F, 150F);
                BindProperty(_roundedRectangle_150_1, "Offset", "my.Position-Vector2(75,75)", "my", _roundedRectangle_150_1);
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_150_2()
            {
                if (_roundedRectangle_150_2 != null) { return _roundedRectangle_150_2; }
                var result = _roundedRectangle_150_2 = _c.CreateRoundedRectangleGeometry();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(0F, 20F));
                result.CornerRadius = new Vector2(25F, 25F);
                result.Offset = new Vector2(-75F, -55F);
                result.Size = new Vector2(150F, 150F);
                BindProperty(_roundedRectangle_150_2, "Offset", "my.Position-Vector2(75,75)", "my", _roundedRectangle_150_2);
                return result;
            }

            // - PreComp layer: Static Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<134, 128>, Rotation:8.999991941061564 degrees
                var geometry = Rectangle_150_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 134F, 128F), LinearGradientBrush_0());;
                return result;
            }

            // - PreComp layer: Static Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<312, 128>, Rotation:8.999991941061564 degrees
                var geometry = Rectangle_150_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 312F, 128F), RadialGradientBrush_0());;
                return result;
            }

            // - PreComp layer: Static Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<482, 129>, Rotation:8.999991941061564 degrees
                var geometry = RoundedRectangle_150_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 482F, 129F), LinearGradientBrush_1());;
                return result;
            }

            // - PreComp layer: Static Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<660, 129>, Rotation:8.999991941061564 degrees
                var geometry = RoundedRectangle_150_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 660F, 129F), RadialGradientBrush_1());;
                return result;
            }

            // - PreComp layer: Animated Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<130, 342>, Rotation:8.999991941061564 degrees
                var geometry = Rectangle_150_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 130F, 342F), LinearGradientBrush_2());;
                return result;
            }

            // - PreComp layer: Animated Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Offset:<308, 342>, Rotation:8.999991941061564 degrees
                var geometry = Rectangle_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 308F, 342F), RadialGradientBrush_2());;
                return result;
            }

            // - PreComp layer: Animated Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                if (_spriteShape_06 != null) { return _spriteShape_06; }
                var result = _spriteShape_06 = _c.CreateSpriteShape(RoundedRectangle_150_1());
                result.FillBrush = LinearGradientBrush_3();
                return result;
            }

            // - PreComp layer: Animated Rects
            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                if (_spriteShape_07 != null) { return _spriteShape_07; }
                var result = _spriteShape_07 = _c.CreateSpriteShape(RoundedRectangle_150_2());
                result.FillBrush = RadialGradientBrush_3();
                return result;
            }

            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<192, 596>, Rotation:8.999991941061564 degrees
                var geometry = Rectangle_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 192F, 596F), LinearGradientBrush_4());;
                return result;
            }

            // Layer aggregator
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<628, 736>, Rotation:8.999988861798546 degrees, Scale:<1.62735, 1.6635401>,
                // Skew:<1.12535155E-08, 0>
                var geometry = Rectangle_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.60731459F, 0.254573643F, -0.260235012F, 1.64305913F, 628F, 736F), LinearGradientBrush_5());;
                return result;
            }

            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                // Offset:<590, 572>, Rotation:8.999991941061564 degrees
                var geometry = PathGeometry();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.987688363F, 0.156434476F, -0.156434476F, 0.987688363F, 590F, 572F), LinearGradientBrush_6());;
                return result;
            }

            // Transforms for Static Rects Scale(1,1,0)
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(1000F, 1000F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // Transforms for Animated Rects Scale(1,1,0)
            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(1000F, 1000F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                // Transforms for White Solid 1 Scale(1,1,0)
                children.InsertAtTop(SpriteVisual_0());
                // PreComp layer: Static Rects
                children.InsertAtTop(ContainerVisual_0());
                // PreComp layer: Animated Rects
                children.InsertAtTop(ContainerVisual_1());
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            ExpressionAnimation RootProgress()
            {
                if (_rootProgress != null) { return _rootProgress; }
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            InsetClip InsetClip_0()
            {
                if (_insetClip_0 != null) { return _insetClip_0; }
                var result = _insetClip_0 = _c.CreateInsetClip();
                return result;
            }

            LinearEasingFunction LinearEasingFunction_0()
            {
                return (_linearEasingFunction_0 == null)
                    ? _linearEasingFunction_0 = _c.CreateLinearEasingFunction()
                    : _linearEasingFunction_0;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_9_to_9()
            {
                // Frame 0.
                if (_rotationAngleInDegreesScalarAnimation_9_to_9 != null) { return _rotationAngleInDegreesScalarAnimation_9_to_9; }
                var result = _rotationAngleInDegreesScalarAnimation_9_to_9 = CreateScalarKeyFrameAnimation(0F, 9F, HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, 20F, LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, 9F, LinearEasingFunction_0());
                return result;
            }

            // PreComp layer: Static Rects
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1000F, 1000F);
                var shapes = result.Shapes;
                // RotationDegrees:9, Offset:<134, 128>
                shapes.Add(SpriteShape_00());
                // RotationDegrees:9, Offset:<312, 128>
                shapes.Add(SpriteShape_01());
                // RotationDegrees:9, Offset:<482, 129>
                shapes.Add(SpriteShape_02());
                // RotationDegrees:9, Offset:<660, 129>
                shapes.Add(SpriteShape_03());
                return result;
            }

            // PreComp layer: Animated Rects
            // Layer aggregator
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1000F, 1000F);
                var shapes = result.Shapes;
                // RotationDegrees:9, Offset:<130, 342>
                shapes.Add(SpriteShape_04());
                // RotationDegrees:9, Offset:<308, 342>
                shapes.Add(SpriteShape_05());
                // Rectangle Path 1
                shapes.Add(SpriteShape_06());
                // Rectangle Path 1
                shapes.Add(SpriteShape_07());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_2()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1000F, 1000F);
                var shapes = result.Shapes;
                // RotationDegrees:9, Offset:<192, 596>
                shapes.Add(SpriteShape_08());
                // Scale:1.62735,1.66354, RotationDegrees:9, Offset:<628, 736>
                shapes.Add(SpriteShape_09());
                // RotationDegrees:9, Offset:<590, 572>
                shapes.Add(SpriteShape_10());
                return result;
            }

            // SolidLayerRectangle
            SpriteVisual SpriteVisual_0()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(1000F, 1000F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                result.Brush = ColorBrush_White();
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // EndPointSource
            Vector2KeyFrameAnimation EndPointSourceVector2Animation()
            {
                // Frame 0.
                if (_endPointSourceVector2Animation != null) { return _endPointSourceVector2Animation; }
                var result = _endPointSourceVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(20F, 20F), HoldThenStepEasingFunction());
                // Frame 71.
                result.InsertKeyFrame(0.473333299F, new Vector2(20F, 106F), LinearEasingFunction_0());
                // Frame 149.
                result.InsertKeyFrame(0.99333334F, new Vector2(20F, 20F), LinearEasingFunction_0());
                return result;
            }

            // - - PreComp layer: Animated Rects
            // - Layer aggregator
            // Rectangle Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(478F, 343F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(492F, 375F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(478F, 343F), LinearEasingFunction_0());
                return result;
            }

            // - - PreComp layer: Animated Rects
            // - Layer aggregator
            // Rectangle Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(656F, 343F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(675F, 343F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(656F, 343F), LinearEasingFunction_0());
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 20F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(50F, 20F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(0F, 20F), LinearEasingFunction_0());
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 20F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(-36F, 0F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(0F, 20F), LinearEasingFunction_0());
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 20F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(0F, -10F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(0F, 20F), LinearEasingFunction_0());
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_3()
            {
                // Frame 0.
                if (_positionVector2Animation_3 != null) { return _positionVector2Animation_3; }
                var result = _positionVector2Animation_3 = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 71.
                result.InsertKeyFrame(0.473333299F, new Vector2(97F, 0F), LinearEasingFunction_0());
                // Frame 149.
                result.InsertKeyFrame(0.99333334F, new Vector2(0F, 0F), LinearEasingFunction_0());
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(150F, 150F), HoldThenStepEasingFunction());
                // Frame 72.
                result.InsertKeyFrame(0.479999989F, new Vector2(88F, 88F), LinearEasingFunction_0());
                // Frame 150.
                result.InsertKeyFrame(1F, new Vector2(150F, 150F), LinearEasingFunction_0());
                return result;
            }

            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_1()
            {
                // Frame 0.
                if (_sizeVector2Animation_1 != null) { return _sizeVector2Animation_1; }
                var result = _sizeVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(150F, 150F), HoldThenStepEasingFunction());
                // Frame 71.
                result.InsertKeyFrame(0.473333299F, new Vector2(228F, 228F), LinearEasingFunction_0());
                // Frame 149.
                result.InsertKeyFrame(0.99333334F, new Vector2(150F, 150F), LinearEasingFunction_0());
                return result;
            }

            // StartPointSource
            Vector2KeyFrameAnimation StartPointSourceVector2Animation()
            {
                // Frame 0.
                if (_startPointSourceVector2Animation != null) { return _startPointSourceVector2Animation; }
                var result = _startPointSourceVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(-22F, -20F), HoldThenStepEasingFunction());
                // Frame 71.
                result.InsertKeyFrame(0.473333299F, new Vector2(31F, -20F), LinearEasingFunction_0());
                // Frame 149.
                result.InsertKeyFrame(0.99333334F, new Vector2(-22F, -20F), LinearEasingFunction_0());
                return result;
            }

            internal CodeGen_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(1000F, 1000F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                StartProgressBoundAnimation(_linearGradientBrush_4, "StartPointSource", StartPointSourceVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_linearGradientBrush_4, "EndPointSource", EndPointSourceVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_linearGradientBrush_5, "StartPointSource", StartPointSourceVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_linearGradientBrush_5, "EndPointSource", EndPointSourceVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_rectangle_0, "Size", SizeVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_rectangle_1, "Position", PositionVector2Animation_3(), RootProgress());
                StartProgressBoundAnimation(_rectangle_1, "Size", SizeVector2Animation_1(), RootProgress());
                StartProgressBoundAnimation(_rectangle_2, "Position", PositionVector2Animation_3(), RootProgress());
                StartProgressBoundAnimation(_rectangle_2, "Size", SizeVector2Animation_1(), RootProgress());
                StartProgressBoundAnimation(_rectangle_150_1, "Position", PositionVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_roundedRectangle_150_1, "Position", PositionVector2Animation_1(), RootProgress());
                StartProgressBoundAnimation(_roundedRectangle_150_2, "Position", PositionVector2Animation_2(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_06, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_9_to_9(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_06, "Offset", OffsetVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_07, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_9_to_9(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_07, "Offset", OffsetVector2Animation_1(), RootProgress());
            }

            public void DestroyAnimations()
            {
                _linearGradientBrush_4.StopAnimation("StartPointSource");
                _linearGradientBrush_4.StopAnimation("EndPointSource");
                _linearGradientBrush_5.StopAnimation("StartPointSource");
                _linearGradientBrush_5.StopAnimation("EndPointSource");
                _rectangle_0.StopAnimation("Size");
                _rectangle_1.StopAnimation("Position");
                _rectangle_1.StopAnimation("Size");
                _rectangle_2.StopAnimation("Position");
                _rectangle_2.StopAnimation("Size");
                _rectangle_150_1.StopAnimation("Position");
                _roundedRectangle_150_1.StopAnimation("Position");
                _roundedRectangle_150_2.StopAnimation("Position");
                _spriteShape_06.StopAnimation("RotationAngleInDegrees");
                _spriteShape_06.StopAnimation("Offset");
                _spriteShape_07.StopAnimation("RotationAngleInDegrees");
                _spriteShape_07.StopAnimation("Offset");
            }

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 12);
            }
        }
    }
}
