// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace SimpleIslandApp
{
    /* The following code is scenario/feature-specific IDL.
    Samples authors should modify these runtime classes as appropriate. */

    /*[default_interface]
    runtimeclass Scenario1_CustomControl : Microsoft.UI.Xaml.Controls.Page
    {
        Scenario1_CustomControl();        
    }

    [default_interface]
    runtimeclass Scenario2_UserControl : Microsoft.UI.Xaml.Controls.Page
    {
        Scenario2_UserControl();
    }*/

     /* The following code is template-specific IDL.
     These runtime classes are the same across all C++/WinRT WinUI samples. */

    [default_interface]
    runtimeclass MainPage
    {
        MainPage();
        static MainPage Current();
        //void NotifyUser(String strMessage, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
    }

}
