namespace LottieIsland
{
    [default_interface]
    runtimeclass LottieContentIsland
    {
        LottieContentIsland(Microsoft.UI.Composition.Compositor compositor);

        Microsoft.UI.Content.ContentIsland Island{ get; };

        LottieWinRT.LottieVisualSourceWinRT AnimatedVisualSource;

        Windows.Foundation.TimeSpan Duration{ get; };

        Boolean IsAnimationLoaded{ get; };

        Boolean IsPlaying{ get; };

        Double PlaybackRate;

        void Pause();

        Windows.Foundation.IAsyncAction PlayAsync(Double fromProgress, Double toProgress, Boolean looped);

        void Resume();

        void Stop();


    }
}
