namespace LottieIsland
{
    [default_interface]
    runtimeclass LottieContentIsland
    {
        LottieContentIsland(Microsoft.UI.Composition.Compositor compositor);

        Int32 MyProperty;

        Microsoft.UI.Content.ContentIsland Island{ get; };

        // TODO: actually give this the right type
        Microsoft.UI.Xaml.Controls.IAnimatedVisualSource AnimatedVisualSource;

        Windows.Foundation.TimeSpan Duration{ get; };

        Boolean IsAnimationLoaded{ get; };

        Boolean IsPlaying{ get; };

        void Pause();

        Windows.Foundation.IAsyncAction PlayAsync(Double fromProgress, Double toProgress, Boolean looped);

        void Resume();

        void Stop();
    }
}
